dist: xenial
language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'

install:
  - pip install pytest pytest-console-scripts
  - pip install pytest-cov
  - pip install coveralls
  - pip install -r requirements.txt
  - pip install -e .
  
script:
  - py.test --cov=mboot tests/*
  
after_success:
  - coveralls
